name: chained-deployment

on:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  dev:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and capture variable: ${{ variable.SUBNET }}
          echo test, and testing secret: ${{ secrets.SUBNET }}
  prod:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: PROD
    steps:
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and capture variable: ${{ variable.SUBNET }}
          echo test, and testing secret: ${{ secrets.SUBNET }}
